import { useEffect, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Check, ChevronRight, Cpu, Download, Globe2, Layers3, LoaderCircle, MessageSquareText, Plus, Send, ShieldCheck, Sparkles, Waves } from 'lucide-react';
import { HORIZONS, type ChatMessage, type Health, type Horizon, type MarketQuote, type Symbol } from '../shared/types';
import { exportJson, horizonLabel, money, percent, timeLabel } from './utils';

export default function MarketChat({ messages, setMessages, send, busy, error, horizon, setHorizon, markets, assetCount, health, analyze }: {
  messages: ChatMessage[];
  setMessages: (messages: ChatMessage[]) => void;
  send: (message: string) => Promise<boolean>;
  busy: boolean;
  error: string;
  horizon: Horizon;
  setHorizon: (horizon: Horizon) => void;
  markets: MarketQuote[];
  assetCount: number;
  health: Health | null;
  analyze: (symbol: Symbol) => void;
}) {
  const [draft, setDraft] = useState('');
  const transcript = useRef<HTMLDivElement>(null);
  const input = useRef<HTMLTextAreaElement>(null);
  const available = Boolean(health?.configured && !health.demo && markets.length && markets.every(market => !market.stale));
  useEffect(() => { if (messages.length && transcript.current) transcript.current.scrollTo({ top: transcript.current.scrollHeight, behavior: 'smooth' }); }, [messages.length, busy]);
  async function submit() { if (draft.trim().length < 3 || busy || !available) return; const text = draft.trim(); setDraft(''); if (!(await send(text))) setDraft(text); }
  const prompts = ['Which crypto is the best buy right now?', 'Find liquid assets with a strong trend and less volatility.', 'Compare BTC, ETH, and SOL. Which setup looks strongest?', 'Exclude stablecoins and avoid chasing today’s biggest pumps.'];
  return <div className="chat-layout"><section className="panel chat-main"><div className="panel-title"><div><span className="lime-icon"><MessageSquareText size={17} /></span><h2>Ask the market</h2><span className="model-badge">JEV 1.13</span></div><div className="chat-toolbar"><button className="icon-button" aria-label="Export chat" disabled={!messages.length || busy} onClick={() => exportJson(messages, 'jev-market-chat.json')}><Download size={15} /></button><button className="icon-button" aria-label="New conversation" disabled={!messages.length || busy} onClick={() => { setMessages([]); setDraft(''); input.current?.focus(); }}><Plus size={18} /></button></div></div>
    <div ref={transcript} className="chat-transcript" role="log" aria-live="polite" aria-label="Market conversation">
      {!messages.length && <div className="chat-welcome"><span className="chat-orb"><Waves size={35} /></span><span className="eyebrow">THE ENTIRE MARKET. ONE CONVERSATION.</span><h2>Find your next research candidate.</h2><p>Tell JEV what you’re looking for. It will scan all {markets.length || assetCount} available Kraken markets and compare the strongest candidates against your criteria.</p><div className="chat-suggestions">{prompts.map(prompt => <button key={prompt} onClick={() => { setDraft(prompt); input.current?.focus(); }}><span>{prompt}</span><ArrowUpRight size={14} /></button>)}</div></div>}
      {messages.map(message => message.role === 'user' ? <div key={message.id} className="chat-user-message"><span>You</span><p>{message.text}</p></div> : <article key={message.id} className="chat-assistant-message"><div className="chat-assistant-label"><span><Sparkles size={13} /></span><strong>JEV market intelligence</strong><small>{message.result ? timeLabel(message.result.createdAt) : ''}</small></div><p>{message.text}</p>{message.result && <>
        <div className="scan-receipt"><span><Globe2 size={12} />{message.result.scannedCount} markets screened</span><span><Layers3 size={12} />{message.result.evaluatedCount} finalists analyzed</span><span><Check size={12} />{horizonLabel(message.result.horizon)}</span></div>
        {!message.result.winner && <div className="abstain-card"><ShieldCheck size={19} /><div><strong>No purchase candidate selected</strong><span>The model favors waiting. Alternatives are shown for comparison.</span></div></div>}
        <div className="chat-candidates">{message.result.candidates.map((candidate, index) => <div className={`candidate-card ${candidate.symbol === message.result!.winner ? 'top-candidate' : ''}`} key={candidate.symbol}><header><span className="candidate-rank">0{index + 1}</span><div><strong>{candidate.name} <small>{candidate.symbol}</small></strong><span>{candidate.symbol === message.result!.winner ? 'BEST FIT FOR YOUR PROMPT' : 'COMPARISON CANDIDATE'}</span></div><button className="icon-button" aria-label={`Analyze ${candidate.symbol}`} onClick={() => analyze(candidate.symbol)}><ArrowUpRight size={17} /></button></header><div className="candidate-price"><strong>{money(candidate.price)}</strong><span className={candidate.changeToday >= 0 ? 'positive' : 'negative'}>{candidate.changeToday >= 0 ? <ArrowUpRight size={12} /> : <ArrowDownLeft size={12} />}{percent(candidate.changeToday)}<small>today UTC</small></span></div><div className="candidate-metrics"><div><span>24h liquidity</span><b>{money(candidate.volume24h, true)}</b></div><div><span>RSI (14)</span><b>{candidate.rsi.toFixed(1)}</b></div><div><span>EMA trend</span><b className={candidate.trend === 'bullish' ? 'positive' : 'negative'}>{candidate.trend}</b></div></div><div className="candidate-weight"><span>Relative selection weight</span><b>{(candidate.selectionWeight * 100).toFixed(1)}%</b></div><div className="candidate-weight-track"><span style={{ width: `${candidate.selectionWeight * 100}%` }} /></div><ul className="candidate-risks">{candidate.risks.map(risk => <li key={risk}>{risk}</li>)}</ul><button className="candidate-analyze" onClick={() => analyze(candidate.symbol)}>Inspect market & forecast <ArrowRight size={12} /></button></div>)}</div>
        <div className="chat-result-notes"><p>Ranking weights compare finalists and the “no candidate” option ({(message.result.noCandidateWeight * 100).toFixed(1)}%). They are not probabilities of profit. Evidence summaries are assembled from market data; JEV returns structured choices.</p><p>Snapshot {timeLabel(message.result.dataAsOf)} · {message.result.batches} screening calls + 1 final comparison · {(message.result.latencyMs / 1000).toFixed(1)}s{message.result.cost !== null ? ` · $${message.result.cost.toFixed(5)} model cost` : ''}</p>{Boolean(message.result.unavailableSymbols.length || message.result.historyUnavailable.length) && <p>Unavailable quotes: {message.result.unavailableSymbols.join(', ') || 'none'}. Insufficient finalist history: {message.result.historyUnavailable.join(', ') || 'none'}.</p>}</div>
      </>}</article>)}
      {busy && <div className="chat-thinking"><span className="thinking-icon"><LoaderCircle size={18} className="spin" /></span><div><strong>Scanning the market with JEV</strong><p>Comparing all available quotes and checking hourly evidence for finalists. This can take a minute.</p><div className="thinking-dots"><i /><i /><i /></div></div></div>}
      {error && <div className="chat-error" role="alert">{error}</div>}
    </div>
    <form className="chat-composer" onSubmit={event => { event.preventDefault(); void submit(); }}><div className="composer-controls"><span><span className={`status-dot ${available ? '' : 'warning'}`} />{available ? `${markets.length} markets in scope` : health?.demo ? 'Live market data required' : !health?.configured ? 'OpenRouter key required' : 'Waiting for live market data'}</span><label>Horizon<select aria-label="Chat research horizon" value={horizon} disabled={busy} onChange={event => setHorizon(Number(event.target.value) as Horizon)}>{HORIZONS.map(value => <option value={value} key={value}>{horizonLabel(value)}</option>)}</select></label></div><div className="composer-input"><textarea ref={input} aria-label="Market research prompt" placeholder="What should I buy right now? Look across all Kraken cryptocurrencies…" maxLength={1200} rows={2} value={draft} disabled={busy} onChange={event => setDraft(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void submit(); } }} /><button className="chat-send" type="submit" disabled={busy || !available || draft.trim().length < 3} aria-label="Send market research prompt">{busy ? <LoaderCircle size={17} className="spin" /> : <Send size={17} />}</button></div><div className="composer-footer"><span>Enter to scan · Shift + Enter for a new line</span><span>On-demand OpenRouter usage</span></div></form>
  </section><aside className="chat-context"><section className="panel universe-card"><span className="settings-icon"><Globe2 size={24} /></span><span className="eyebrow">YOUR RESEARCH UNIVERSE</span><strong className="universe-number">{assetCount}</strong><h3>Kraken cryptocurrencies</h3><p>Every available USD market is considered. No fixed coin list. No hidden liquidity cutoff.</p><div><span>Live quotes</span><b>{markets.length}</b></div><div><span>Market data</span><b>Kraken spot</b></div><div><span>Decision model</span><b>TypeSafe JEV 1.13</b></div><div><span>Execution</span><b>Research only</b></div></section><section className="panel chat-how"><h3><Cpu size={15} />How JEV selects a candidate</h3><ol><li><span>01</span><div><strong>Read your criteria</strong><p>Risk preferences, liquidity, momentum, and the selected horizon.</p></div></li><li><span>02</span><div><strong>Screen the whole catalog</strong><p>Balanced batches retain three candidates each. No cross-batch probability comparisons.</p></div></li><li><span>03</span><div><strong>Check the finalists</strong><p>Compare hourly trends, RSI, volatility, and recent closes. JEV can select no candidate.</p></div></li></ol></section><div className="chat-context-note"><ShieldCheck size={15} /><p>Live news, order-book depth, and your financial circumstances are outside this scan. A top-ranked candidate is a starting point for research.</p></div></aside></div>;
}
